# Generated by Django 3.2 on 2025-05-05 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_auto_20250312_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='default_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BoardControlRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_requests', to='elevator.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_control_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
