# Generated by Django 4.2.23 on 2025-07-24 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_historicallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('operator', 'Operator')], max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('location', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='HistoricalLocation',
        ),
        migrations.AlterField(
            model_name='location',
            name='authorized_users',
            field=models.ManyToManyField(related_name='accessible_locations', through='elevator.LocationUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
