# Generated by Django 4.2.23 on 2025-07-24 02:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_locationuser_delete_historicallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='elevator.location')),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='elevator.system')),
            ],
        ),
    ]
