# Generated by Django 3.2 on 2025-06-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_auto_20250605_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
