# Generated by Django 4.2.23 on 2025-07-24 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0005_unit_animaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_menus', to='elevator.location')),
            ],
            options={
                'db_table': 'feeding_menus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_types', to='elevator.location')),
            ],
            options={
                'db_table': 'food_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedingMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=2, help_text='Tỷ lệ phần trăm, ví dụ 25.50', max_digits=5)),
                ('feeding_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='elevator.feedingmenu')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='elevator.foodtype')),
            ],
            options={
                'db_table': 'feeding_menu_items',
                'ordering': ['feeding_menu'],
                'unique_together': {('feeding_menu', 'food_type')},
            },
        ),
    ]
