# Generated by Django 4.2.23 on 2025-07-24 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0006_feedingmenu_foodtype_feedingmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_code', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('initial_quantity', models.IntegerField()),
                ('remaining_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_cycles', to='elevator.animaltype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_cycles', to='elevator.location')),
            ],
            options={
                'db_table': 'farming_cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FarmingCyclePond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.IntegerField(help_text='Số lượng thả ở bể này khi bắt đầu vụ')),
                ('remaining_quantity', models.IntegerField(help_text='Số lượng còn lại ở bể này hiện tại')),
                ('farming_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_pond_links', to='elevator.farmingcycle')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_pond_links', to='elevator.pond')),
            ],
            options={
                'db_table': 'farming_cycle_ponds',
                'unique_together': {('farming_cycle', 'pond')},
            },
        ),
        migrations.AddIndex(
            model_name='farmingcycle',
            index=models.Index(fields=['cycle_code'], name='farming_cyc_cycle_c_aa15ca_idx'),
        ),
        migrations.AddIndex(
            model_name='farmingcycle',
            index=models.Index(fields=['status'], name='farming_cyc_status_8558de_idx'),
        ),
    ]
