# Generated by Django 4.2.23 on 2025-07-28 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0008_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingmenuitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_menu_items', to='elevator.unit'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Người được giao nhiệm vụ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('pond', 'Pond'), ('tank', 'Tank'), ('cage', 'Cage')], default='pond', max_length=50),
        ),
        migrations.CreateModel(
            name='WaterQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('discharge_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pump_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.ImageField(blank=True, help_text='Ảnh minh hoạ', null=True, upload_to='water_quality_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('pH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dissolved_oxygen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evaluation', models.IntegerField(help_text='Đánh giá chất lượng (-2: rất xấu → 2: rất tốt)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farming_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_records', to='elevator.farmingcycle')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_records', to='elevator.pond')),
            ],
            options={
                'db_table': 'water_quality_records',
                'ordering': ['-record_date'],
                'unique_together': {('farming_cycle', 'pond', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='DensityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('density', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farming_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='density_records', to='elevator.farmingcycle')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='density_records', to='elevator.pond')),
            ],
            options={
                'db_table': 'density_records',
                'ordering': ['-record_date'],
                'unique_together': {('farming_cycle', 'pond', 'record_date')},
            },
        ),
    ]
