# Generated by Django 4.2.23 on 2025-07-28 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0009_feedingmenuitem_unit_task_assigned_to_unit_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('feed', 'Thức ăn'), ('equipment', 'Thiết bị')], max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='elevator.location')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='elevator.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='elevator.product')),
            ],
            options={
                'db_table': 'stock_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('mass', 'Khối lượng'), ('volume', 'Thể tích'), ('count', 'Số lượng'), ('custom', 'Khác')], default='pond', max_length=50),
        ),
        migrations.CreateModel(
            name='StockTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_details', to='elevator.product')),
                ('stock_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='elevator.stocktransaction')),
            ],
            options={
                'db_table': 'stock_transaction_details',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='elevator.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='elevator.product')),
            ],
            options={
                'db_table': 'inventories',
                'unique_together': {('location', 'product')},
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('health_status', models.IntegerField(help_text='Tình trạng sức khoẻ (-2 đến 2)')),
                ('feces_status', models.IntegerField(help_text='Tình trạng phân (-2 đến 2)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farming_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='elevator.farmingcycle')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='elevator.pond')),
            ],
            options={
                'db_table': 'health_records',
                'ordering': ['-record_date'],
                'unique_together': {('farming_cycle', 'pond', 'record_date')},
            },
        ),
    ]
